### ISSUE TITLE
Database gets cleared randomly after some time

### ISSUE THREAD

**Issue by SumiGovindaraju** [Team254/cheesy-video#2]
I don't know why but if I reindex the database, everything will be fine for a little while, but after some a short period of time (I'm not exactly sure how long), the database will be cleared and no videos will be there.

**Comment by patfair** [comment]
There's a crontab entry (it was in the ubuntu user but I moved it to team254 just now so you can see) which reindexes the videos every 15 minutes by executing `curl http://localhost:9004/reindex_videos`. Maybe that's what is responsible?

**Comment by SumiGovindaraju** [comment]
Yes. Reindexing requires authentication, and just going to [video.team254.com/reindex_videos](https://video.team254.com/reindex_videos) clears the database, for some reason. I'll try and fix that part of the script, but in the meantime, I'm going to remove that cron job, that should fix the problem.

**Comment by neyre** [comment]
We shouldn't need cheesy-video anymore without Ooyala, right?

**Comment by SumiGovindaraju** [comment]
@neyre: This will be easier to update the JSON file for [team254.com/videos](https://www.team254.com/videos/) than updating [videoindex.json](https://github.com/Team254/Website/blob/master/videoindex.json) manually. Btw, removing the cronjob fixed this issue.

**Comment by neyre** [comment]
Sorry I might be missing something. Does this app do anything except scrape our Ooyala account and make an API for it?

**Comment by SumiGovindaraju** [comment]
I adapted this app, so it gets all of the videos from playlists (w/ years as names) from our Youtube account. What I think we should keep it for, is if you go to [/json](https://video.team254.com/json), it can provide the most up to date version of all of our playlists on Youtube for use in https://team254.com/videos. This would be easier to use, than always manually changing videoindex.json in the Website repository, everytime we add a new video to a playlist.

**Comment by neyre** [comment]
Sorry, I missed that update. My bad.

So is this resolved then? We've removed the cron job and now you can only reindex manually?

Can anyone clear the database just by going to https://video.team254.com/reindex_videos and hitting the button? If so, that seems like a bug.

**Comment by SumiGovindaraju** [comment]
I'll work out that bug, but for now this issue is resolved.
